create database board;
use board;


CREATE TABLE TB_LOGIN_HISTORY (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_MEMBER (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    nick_name VARCHAR(100),
    is_email_auth boolean,
    is_in_active boolean,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    profile_image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TB_EMAIL_AUTH (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) NOT NULL,
    uuid VARCHAR(225) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_CODE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(100) NOT NULL ,
    code_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO TB_CODE (group_name, code_name) VALUES
('POST_CATEGORY', '공지사항'),
('POST_CATEGORY', '질문과답변'),
('POST_CATEGORY', '자유게시판'),
('POST_CATEGORY', '갤러리'),
('POST_ORDER', '최신순'),
('POST_ORDER', '오래된순'),
('POST_ORDER', '조회수순'),
('POST_ORDER', '좋아요순'),
('POST_ORDER', '싫어요순'),
('POST_ORDER', '댓글수순'),
('POST_SEARCH', '제목'),
('POST_SEARCH', '작성자'),
('POST_SEARCH', '내용'),
('POST_RANGE', '공개'),
('POST_RANGE', '비공개'),
('POST_RANGE', '보호'),
('POST_RANGE', '익명');

CREATE TABLE TB_POST (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_idx BIGINT NOT NULL,
    category_idx BIGINT NOT NULL,
    range_idx BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content LONGTEXT NOT NULL,
    view_count BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx),
    FOREIGN KEY (category_idx) REFERENCES TB_CODE(idx),
    FOREIGN KEY (range_idx) REFERENCES TB_CODE(idx)
);

CREATE TABLE TB_POST_IMAGE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_idx) REFERENCES TB_POST(idx)
);

CREATE TABLE TB_LIKE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT,
    comment_idx BIGINT,
    member_idx BIGINT NOT NULL,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx)
);

CREATE TABLE TB_UNLIKE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT,
    comment_idx BIGINT,
    member_idx BIGINT NOT NULL,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx)
);

CREATE TABLE TB_COMMENT(
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT NOT NULL,
    member_idx BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (post_idx) REFERENCES TB_POST(idx),
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx)
);