create database board1;
use board1;

CREATE TABLE TB_LOGIN_HISTORY (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_MEMBER (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    nick_name VARCHAR(100),
    is_email_auth boolean,
    is_in_active boolean,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    profile_image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TB_EMAIL_AUTH (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) NOT NULL,
    uuid VARCHAR(225) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_CODE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(100) NOT NULL ,
    code_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO TB_CODE (group_name, code_name) VALUES
('CATEGORY', '공지사항'),
('CATEGORY', '질문과답변'),
('CATEGORY', '자유게시판'),
('CATEGORY', '갤러리'),
('ORDER', '최신순'),
('ORDER', '오래된순'),
('ORDER', '조회수순'),
('ORDER', '좋아요순'),
('ORDER', '싫어요순'),
('ORDER', '댓글수순'),
('SEARCH', '제목'),
('SEARCH', '작성자'),
('SEARCH', '내용'),
('VISIBILITY', '공개'),
('VISIBILITY', '비공개'),
('VISIBILITY', '익명'),
('VISIBILITY', '보호');

CREATE TABLE TB_POST (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_idx BIGINT NOT NULL,
    category_idx BIGINT NOT NULL,
    range_idx BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content LONGTEXT NOT NULL,
    view_count BIGINT DEFAULT 0,
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx),
    FOREIGN KEY (category_idx) REFERENCES TB_CODE(idx),
    FOREIGN KEY (range_idx) REFERENCES TB_CODE(idx)
);

CREATE TABLE TB_POST_IMAGE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_idx) REFERENCES TB_POST(idx) ON DELETE CASCADE
);

CREATE TABLE TB_COMMENT(
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT NOT NULL,
    member_idx BIGINT NOT NULL,
    parent_comment_idx BIGINT,
    content LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (post_idx) REFERENCES TB_POST(idx) ON DELETE CASCADE,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx),
    FOREIGN KEY (parent_comment_idx) REFERENCES TB_COMMENT(idx) ON DELETE CASCADE
);

CREATE TABLE TB_LIKE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT,
    comment_idx BIGINT,
    member_idx BIGINT NOT NULL,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx),
    FOREIGN KEY (post_idx) REFERENCES TB_POST(idx) ON DELETE CASCADE,
    FOREIGN KEY (comment_idx) REFERENCES TB_COMMENT(idx) ON DELETE CASCADE
);

CREATE TABLE TB_UNLIKE (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_idx BIGINT,
    comment_idx BIGINT,
    member_idx BIGINT NOT NULL,
    FOREIGN KEY (member_idx) REFERENCES TB_MEMBER(idx),
    FOREIGN KEY (post_idx) REFERENCES TB_POST(idx) ON DELETE CASCADE,
    FOREIGN KEY (comment_idx) REFERENCES TB_COMMENT(idx) ON DELETE CASCADE
);

CREATE TABLE TB_RANK (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    ranking INT NOT NULL,
    flag VARCHAR(1) NOT NULL COMMENT '랭킹 구분 (V: 조회수, L: 좋아요, U: 싫어요, C: 댓글수)',
    title VARCHAR(255) NOT NULL,
    post_idx BIGINT NOT NULL,
    view_count INT DEFAULT 0,
    like_count INT DEFAULT 0,
    unlike_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (post_idx) REFERENCES tb_post(idx) ON DELETE CASCADE,
    INDEX idx_flag (flag),
    INDEX idx_ranking (ranking)
);